version: "2"

services:

  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${HUBGREP_POSTGRES_PASSWORD}

  redis:
    image: redis

  service:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env

    restart: ${RESTART}
    
    # override the about page text
    # hubgrep_about.md is the default path
    #environment:
    #    HUBGREP_ABOUT_MARKDOWN_FILE: hubgrep_about.md
    
    # uplink port to host
    

    # to copy static files out of the container
    # set STATIC_PATH in .env, and link 
    # the folder to the host
    #volumes:
    #  - "./host_static:${STATIC_PATH}"

    ports:
      - 8080:8080
    command:
      - /bin/bash
      - -c
      - |
         if [ -z ${STATIC_PATH} ]; then
           echo "";
         else
           flask cli copy-static "${STATIC_PATH}"
         fi
         gunicorn --bind 0.0.0.0:8080 "hubgrep:create_app()"
volumes:
  pgdata:
