version: "3.1"

services:

  test_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: hubgrep
      POSTGRES_PASSWORD: hubgrep
      POSTGRES_DB: hubgrep
    ports:
      - 5432:5432
    networks:
      - hubgrep_search

  service:
    build: .
    volumes:
    - ./:/var/task

    restart: ${RESTART}

    # uplink port to host
    ports:
      - 8080:8080

    command: >
          bash -ic " \
            pip install -r requirements.txt
            flask run --host 0.0.0.0 --port 8080
            "
    tty: true
    networks:
      - hubgrep_search
  
networks:
  hubgrep_search:
  hubgrep:
    name: hubgrep
