version: "2"

services:

  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${HUBGREP_POSTGRES_PASSWORD}

  service:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env

    restart: ${RESTART}
    
    # override the about page text
    # hubgrep_about.md is the default path
    #environment:
    #    HUBGREP_ABOUT_MARKDOWN_FILE: hubgrep_about.md
    
    # uplink port to host
    

    # to copy static files out of the container
    # set STATIC_PATH in .env, and link 
    # the folder to the host
    volumes:
      - "./static:${STATIC_PATH}"

    ports:
      - 127.0.0.1:8080:8080
    command:
      - /bin/bash
      - -c
      - |
         if [ -z ${STATIC_PATH} ]; then
           echo "";
         else
           flask cli copy-static "${STATIC_PATH}"
         fi
         gunicorn --bind 0.0.0.0:8080 "hubgrep:create_app()"
  
  sphinx:
    image: macbre/sphinxsearch:3.3.1
    env_file: .env
    ports:
    - "127.0.0.1:9312:9312" # bind to local interface only!
    - "127.0.0.1:9306:9306"
    volumes:
    - ./sphinx_data:/var/lib/sphinx/data  # directory where sphinx will store index data
    - ./sphinx.conf:/opt/sphinx/conf/sphinx.conf  # SphinxSE configuration file


volumes:
  pgdata:
