version: "2"

services:

  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${HUBGREP_POSTGRES_PASSWORD}

  service:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env

    restart: ${RESTART}
    
    # override the about page text
    # hubgrep_about.md is the default path
    #environment:
    #    HUBGREP_ABOUT_MARKDOWN_FILE: hubgrep_about.md
    
    # uplink port to host
    

    # to copy static files out of the container
    # set STATIC_PATH in .env, and link 
    # the folder to the host
    volumes:
      - "./static:${STATIC_PATH}"

    ports:
      - 127.0.0.1:8080:8080
    command:
      - /bin/bash
      - -c
      - |
         if [ -z ${STATIC_PATH} ]; then
           echo "";
         else
           flask cli copy-static "${STATIC_PATH}"
         fi
         gunicorn --bind 0.0.0.0:8080 "hubgrep:create_app()"
  
  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    env_file: .env
    restart: always
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./manticore_data:/var/lib/manticore
      - ./manticore.conf:/etc/manticoresearch/manticore.conf # uncommment if you use a custom config
volumes:
  pgdata:
