version: 2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: docker-compose -f docker-compose-ci.yml up -d test_postgres
      - run: docker-compose -f docker-compose-ci.yml run --rm service bash -c "pip install -r requirements.txt && ./manage.sh test"
   
    

    
workflows:
  main:
    jobs:
      - build-and-test

