"""empty message

Revision ID: 167e105549bf
Revises: ff3de74a16f4
Create Date: 2021-03-21 12:29:18.604061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167e105549bf'
down_revision = 'ff3de74a16f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hosting_service_type_key', 'hosting_service', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hosting_service_type_key', 'hosting_service', ['type'])
    # ### end Alembic commands ###
