"""empty message

Revision ID: 9e7b17ff17a8
Revises: e5cb19b1b5d3
Create Date: 2021-07-06 19:01:57.766707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7b17ff17a8'
down_revision = 'e5cb19b1b5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('import_timestamp', sa.Float(), nullable=False))
    op.alter_column('repositories', 'foreign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('repositories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('repositories', 'foreign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('repositories', 'import_timestamp')
    # ### end Alembic commands ###
