"""empty message

Revision ID: 085a5ecc3230
Revises: 163ee3b91851
Create Date: 2021-08-18 13:30:59.001456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085a5ecc3230'
down_revision = '163ee3b91851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_empty', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'repositories', 'hosting_service', ['hosting_service_id'], ['id'])
    op.drop_column('repositories', 'is_disabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'is_empty')
    # ### end Alembic commands ###
