"""empty message

Revision ID: eb0b73bbb1f1
Revises: c618907185dd
Create Date: 2021-06-17 14:28:41.287904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0b73bbb1f1'
down_revision = 'c618907185dd'
branch_labels = None
depends_on = None


from hubgrep import db

class HostingService(db.Model):

    



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('api_key', sa.String(length=500), nullable=True))
    op.add_column('hosting_service', sa.Column('custom_config', sa.Text(), nullable=True))
    op.alter_column('hosting_service', 'label',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.drop_column('hosting_service', 'config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('hosting_service', 'label',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('hosting_service', 'custom_config')
    op.drop_column('hosting_service', 'api_key')
    # ### end Alembic commands ###
