"""empty message

Revision ID: 380ab636fcaf
Revises: 5ac5c2f16026
Create Date: 2021-06-18 12:45:53.495631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380ab636fcaf'
down_revision = '5ac5c2f16026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hosting_service', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('hosting_service', 'config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('hosting_service', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
