"""empty message

Revision ID: e5cb19b1b5d3
Revises: 691fa93dfbcc
Create Date: 2021-07-05 23:40:05.400134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cb19b1b5d3'
down_revision = '691fa93dfbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'forks_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('repositories', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('repositories', 'stars_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('repositories', 'subscribers_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'subscribers_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('repositories', 'stars_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('repositories', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('repositories', 'forks_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
