"""empty message

Revision ID: 6a9c160247e2
Revises: 085a5ecc3230
Create Date: 2021-08-22 22:09:59.657330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9c160247e2'
down_revision = '085a5ecc3230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'is_private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
