"""empty message

Revision ID: df57f7a69db0
Revises: 34bb132fca65
Create Date: 2021-08-15 13:42:36.347014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df57f7a69db0'
down_revision = '34bb132fca65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('domain', sa.String(length=500), nullable=True))
    op.drop_column('hosting_service', 'label')
    op.create_foreign_key(None, 'repositories', 'hosting_service', ['hosting_service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.add_column('hosting_service', sa.Column('label', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('hosting_service', 'domain')
    # ### end Alembic commands ###
