"""empty message

Revision ID: 0ee99a87af77
Revises: 44b1424d5fe1
Create Date: 2021-07-09 20:36:28.422764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ee99a87af77'
down_revision = '44b1424d5fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('imported', sa.Boolean(), nullable=True))
    op.drop_column('repositories', 'import_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('import_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('repositories', 'imported')
    # ### end Alembic commands ###
