"""empty message

Revision ID: d9b3964977e4
Revises: 157ce449a792
Create Date: 2021-07-01 09:55:55.548334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b3964977e4'
down_revision = '157ce449a792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'watchers_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('watchers_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
