"""empty message

Revision ID: 8b1767680da6
Revises: 6a9c160247e2
Create Date: 2021-08-23 21:42:36.698443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b1767680da6'
down_revision = '6a9c160247e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'is_private')
    # ### end Alembic commands ###
