"""empty message

Revision ID: 34bb132fca65
Revises: 2e6a53303c9b
Create Date: 2021-08-14 01:31:23.870992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34bb132fca65'
down_revision = '2e6a53303c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_repositories')
    op.add_column('hosting_service', sa.Column('export_timestamp', sa.DateTime(), nullable=True))
    op.add_column('hosting_service', sa.Column('repo_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repositories', 'hosting_service', ['hosting_service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('hosting_service', 'repo_count')
    op.drop_column('hosting_service', 'export_timestamp')
    op.create_table('new_repositories',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('foreign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hosting_service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pushed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stars_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('forks_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_fork', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_disabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_mirror', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('homepage_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('repo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='new_repositories_pkey')
    )
    # ### end Alembic commands ###
