"""empty message

Revision ID: 34bb132fca65
Revises: 2e6a53303c9b
Create Date: 2021-08-14 01:31:23.870992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34bb132fca65'
down_revision = '2e6a53303c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('export_timestamp', sa.DateTime(), nullable=True))
    op.add_column('hosting_service', sa.Column('repo_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repositories', 'hosting_service', ['hosting_service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('hosting_service', 'repo_count')
    op.drop_column('hosting_service', 'export_timestamp')
    # ### end Alembic commands ###
