"""empty message

Revision ID: 163ee3b91851
Revises: df57f7a69db0
Create Date: 2021-08-16 12:59:34.332836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163ee3b91851'
down_revision = 'df57f7a69db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('export_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'repositories', 'hosting_service', ['hosting_service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('hosting_service', 'export_url')
    # ### end Alembic commands ###
