"""empty message

Revision ID: 157ce449a792
Revises: 763b4230745c
Create Date: 2021-07-01 09:54:04.390306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '157ce449a792'
down_revision = '763b4230745c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_id', sa.Integer(), nullable=True),
    sa.Column('hosting_service_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_fork', sa.Boolean(), nullable=True),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=500), nullable=True),
    sa.Column('forks_count', sa.Integer(), nullable=False),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.Column('watchers_count', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('open_issues_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('subscribers_count', sa.Integer(), nullable=False),
    sa.Column('license_name', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['hosting_service_id'], ['hosting_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('repo_index', 'repositories', ['foreign_id', 'hosting_service_id'], unique=False)
    op.drop_table('repository')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hosting_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('namespace', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_fork', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('homepage', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('html_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('forks_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stars_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('watchers_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('open_issues_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_disabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pushed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subscribers_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('license_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hosting_service_id'], ['hosting_service.id'], name='repository_hosting_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='repository_pkey')
    )
    op.drop_index('repo_index', table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
