"""empty message

Revision ID: 763b4230745c
Revises: 9398728b4392
Create Date: 2021-06-30 22:51:27.605052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763b4230745c'
down_revision = '9398728b4392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('api_key', sa.String(length=500), nullable=True))
    op.add_column('hosting_service', sa.Column('custom_config', sa.Text(), nullable=True))
    op.alter_column('hosting_service', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('hosting_service', 'config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('hosting_service', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('hosting_service', 'custom_config')
    op.drop_column('hosting_service', 'api_key')
    # ### end Alembic commands ###
