"""empty message

Revision ID: ff3de74a16f4
Revises: df78a0ac0ece
Create Date: 2021-03-21 11:45:25.525737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3de74a16f4'
down_revision = 'df78a0ac0ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosting_service', sa.Column('frontpage_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosting_service', 'frontpage_url')
    # ### end Alembic commands ###
